### ISSUE TITLE
New gcc warnings broke Encode with perl 5.8.9 on Win32

### ISSUE THREAD

**Issue by pali** [dankogai/p5-encode#113]
In commit https://github.com/dankogai/p5-encode/commit/d92071dba0a9c72e78500825c263f1c90b5a7f15 @rurban added new gcc warning flags `-Werror=declaration-after-statement` and `-Wpointer-sign` which caused compile errors with perl 5.8.9 on Win32. Problem is reported in CPAN Testers Matrix.

See http://www.cpantesters.org/cpan/report/ebf45fc3-6d42-1014-9ffc-b1671f639c1c
> gcc -c  -IEncode 	-s -O2 -DWIN32 -DHAVE_DES_FCRYPT  -DUSE_SITECUSTOMIZE -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -fno-strict-aliasing -DPERL_MSVCRT_READFIX -Werror=declaration-after-statement -Wpointer-sign -s -O2 	  -DVERSION=\"2.90\" 	-DXS_VERSION=\"2.90\"  "-IC:\strawberry\perl\lib\CORE"   Encode.c
cc1.exe: error: unrecognized command line option "-Werror=declaration-after-statement"
cc1.exe: error: unrecognized command line option "-Wpointer-sign"
dmake.EXE:  Error code 129, while making 'Encode.o'

@rurban Can you look at that your commit?

**Comment by rurban** [comment]
Sure, happy to fix it for older gcc's

**Comment by mariopaumann** [comment]
-Werror=declaration-after-statement is not available on 4.1.2 gcc too.

[perl@apacrslnxe1 ~]$ gcc -Werror=declaration-after-statement /tmp/a.c
cc1: error: unrecognized command line option "-Werror=declaration-after-statement"
[perl@apacrslnxe1 ~]$ gcc -Wpointer-sign /tmp/a.c
[perl@apacrslnxe1 ~]$ gcc --version
gcc (GCC) 4.1.2 20080704 (Red Hat 4.1.2-55)

**Comment by rurban** [comment]
Ok, that's a bit crazy, but thanksfully we don't need this flag on windows, as we need it for non-windows systems to test for windows.
See the next PR
