### ISSUE TITLE
Two competing bugtrackers

### ISSUE THREAD

**Issue by ribasushi** [dankogai/p5-encode#14]
You seem to accept issues both via RT and GitHub - please clarify if this is intentional, or if one of the channels should be preferred. By the way there is a way to both get search.cpan.org/metacpan to link to github directly OR to disable github issues.

Cheers

**Comment by dolmen** [comment]
@dankogai This question is still relevant.

**Comment by dolmen** [comment]
I was still expecting a response to that question. Closing without even a comment is really disturbing. Well, not that much as the issue was already more than 2.5 years old...

**Comment by karenetheridge** [comment]
I'd also be interested in knowing where I should be reporting issues.
