### ISSUE TITLE
Pure perl mode ?

### ISSUE THREAD

**Issue by tdegeus** [dankogai/p5-encode#163]
Can this module also be used in pure perl mode (i.e. without compiling stuff) ?

**Comment by pali** [comment]
Hello! Encode is core perl module, part of perl itself, uses core perl APIs and therefore cannot be pure perl.

**Comment by tdegeus** [comment]
HI! Ah thanks, I though it was an add-on. So I do not need this: https://github.com/conda-forge/staged-recipes/pull/17143 ?
