### ISSUE TITLE
Encode with a non-default fallback destroys its input if it contains a NUL character

### ISSUE THREAD

**Issue by ap** [dankogai/p5-encode#22]
If a string containing a `\0` is passed to `decode()` *with a non-default fallback mode*, Encode empties the input string.

Test case:

````perl
#!/usr/bin/perl
use 5.016;
use warnings;
 
use Encode 2.62 'decode';
use Devel::Peek 'Dump';
 
my $c = (" " x 10) . chr(0) . (" " x 10);
 
Dump $c;
decode("utf8", $c); # return ignored, so no-op
Dump $c;
decode("utf8", $c, Encode::FB_CROAK); # should be a no-op also
Dump $c;
````

Output:
````
SV = PV(0x7ff544001180) at 0x7ff54402ddc0
  REFCNT = 1
  FLAGS = (PADMY,POK,pPOK)
  PV = 0x10c507110 "          \0          "\0
  CUR = 21
  LEN = 32
SV = PV(0x7ff544001180) at 0x7ff54402ddc0
  REFCNT = 1
  FLAGS = (PADMY,POK,pPOK)
  PV = 0x10c507110 "          \0          "\0
  CUR = 21
  LEN = 32
SV = PV(0x7ff544001180) at 0x7ff54402ddc0
  REFCNT = 1
  FLAGS = (PADMY,POK,pPOK)
  PV = 0x10c507110 ""\0
  CUR = 0
  LEN = 32
````

That’s… horrifically broken.

The condition appears to be whether there is any `\0` anywhere in the string – regardless of where: beginning, end, middle, no matter. Length: also irrelevant. It only matters that a) there is a non-default fallback mode and b) there is `\0` in the input string.

**Comment by ap** [comment]
@dankogai: you never weighed in on this, so I don’t know if you do consider this not a bug. But I can still reproduce it with perl 5.22.1 and Encode 2.82. Should I re-file a new ticket for it?

**Comment by dankogai** [comment]
I think this behavior is correct.

````perl
#!/usr/bin/perl
use 5.016;
use warnings;

use Encode 2.62 'decode';
use Devel::Peek 'Dump';

my $c = (" " x 10) . chr(0) . (" " x 10);
my $s;

print STDERR '$c:'; Dump $c;
print STDERR '$s:'; Dump $s;
$s = decode("utf8", $c); # return ignored, so no-op
print STDERR '$c:'; Dump $c;
print STDERR '$s:'; Dump $s;
decode("utf8", $c, Encode::FB_CROAK); # should be a no-op also
print STDERR '$c:'; Dump $c;
print STDERR '$s:'; Dump $s;
````

````
$c:SV = PV(0x7f84a8806488) at 0x7f84a9042fd8
  REFCNT = 1
  FLAGS = (POK,pPOK)
  PV = 0x7f84a8704298 "          \0          "\0
  CUR = 21
  LEN = 23
$s:SV = NULL(0x0) at 0x7f84a902af18
  REFCNT = 1
  FLAGS = ()
$c:SV = PV(0x7f84a8806488) at 0x7f84a9042fd8
  REFCNT = 1
  FLAGS = (POK,IsCOW,pPOK)
  PV = 0x7f84a8704298 "          \0          "\0
  CUR = 21
  LEN = 23
  COW_REFCNT = 0
$s:SV = PV(0x7f84a88066e8) at 0x7f84a902af18
  REFCNT = 1
  FLAGS = (POK,IsCOW,pPOK,UTF8)
  PV = 0x7f84a8700ab8 "          \0          "\0 [UTF8 "          \x{0}          "]
  CUR = 21
  LEN = 23
  COW_REFCNT = 0
$c:SV = PV(0x7f84a8806488) at 0x7f84a9042fd8
  REFCNT = 1
  FLAGS = (POK,pPOK)
  PV = 0x7f84a8704298 ""\0
  CUR = 0
  LEN = 23
$s:SV = PV(0x7f84a88066e8) at 0x7f84a902af18
  REFCNT = 1
  FLAGS = (POK,IsCOW,pPOK,UTF8)
  PV = 0x7f84a8700ab8 "          \0          "\0 [UTF8 "          \x{0}          "]
  CUR = 21
  LEN = 23
  COW_REFCNT = 0
````

* There destination `$s` is identical.
* the source `$c` is cleared because ALL CHARS ARE CONVERTED FINE.  Unless `LEAVE_SRC` is set this is what Encode is documented to do.

**Comment by ap** [comment]
Hmm, looks like you are right. I thought it did different things when NUL is involved vs no NUL, but I cannot reproduce any such case right now. Maybe there was such a case but I didn’t post it and now it’s lost, or I confused myself about the difference in some way when I originally reported this.

It’s not unlikely that I was confused. I must say did not appreciate that `FB_CROAK` does not include `LEAVE_SRC` and what that means. IMO the documentation makes this difficult to find. You have read very carefully to see and understand the point about the `LEAVE_SRC` bit.

I guess I’ll cook up a doc patch to make this more obvious.
