### ISSUE TITLE
Sync with blead

### ISSUE THREAD

**Issue by steve-m-hay** [dankogai/p5-encode#61]
Please can you consider pulling in the patches at 

https://rt.cpan.org/Ticket/Display.html?id=111421

and

https://rt.cpan.org/Ticket/Display.html?id=116196

to sync your next release with what's currently in blead?

Thanks!

**Comment by dankogai** [comment]
Done as requested.

https://github.com/dankogai/p5-encode/commit/f61f6122ea0915b73960df42b1b6ec25e8dc746b
https://github.com/dankogai/p5-encode/commit/cf6ff75f721b58676d44dc3f8d10e3dc8919795e


And I will $Encode::VERSION++ unless travis is irate.

Dan the Maintainer Thereof

**Comment by pali** [comment]
I think all patches are applied, so this ticket can be closed.
