### ISSUE TITLE
g++-6 -fpermissive errors

### ISSUE THREAD

**Issue by rurban** [dankogai/p5-encode#79]
It is a goal to compile perl with g++. 
g++-6 adds stricter -fpermissive checks, which fail in Encode 2.87.
Maybe add more core-compatible warnings to Makefile.PL CCFLAGS:
    -Wpointer-sign, -fpermissive, -Werror=declaration-after-statement

static const array forward declarations are illegal in C++, they need to be extern.
And we cannot just ask $Config{d_cplusplus} since you are allowed to override it via 
`perl Makefile.PL CC=g++-6`.

Some -Wc++11-compat fixes are also missing.

I'll try to come up with PR, as I need it for cperl.

**Comment by pali** [comment]
Hi! Some changes are probably already covered by https://github.com/dankogai/p5-encode/pull/75 and https://github.com/dankogai/p5-encode/commit/d14cc64e5ecf9056f55e6a9671984c3b988f14c6

**Comment by rurban** [comment]
No, I got more in my branch. Works for me fine in core, but I'll test it a bit  more.

**Comment by pali** [comment]
If you already tested your changes it would be great if you create pull request with needed fixes.

**Comment by rurban** [comment]
Already in
